Modify cmd option in Guardfile
Not `bundle exec` cause following error

    Guard::RSpec failed to achieve its <run_all>, exception was:
    > [#CC0CB6320818] NoMethodError: undefined method `match' for nil:NilClass